from __future__ import annotations

import json

from rich.console import Console

from visionscore.models import (
    AIFeedback,
    AestheticScore,
    AnalysisReport,
    CompositionScore,
    Grade,
    ImageMeta,
    TechnicalScore,
)
from visionscore.output.cli_report import render_report
from visionscore.output.json_report import format_json
from visionscore.output.markdown_report import format_markdown


def _full_report() -> AnalysisReport:
    return AnalysisReport(
        image_meta=ImageMeta(path="test.jpg", width=200, height=200, format="JPEG"),
        technical=TechnicalScore(
            sharpness=70, exposure=75, noise=80, dynamic_range=65, overall=72.5
        ),
        aesthetic=AestheticScore(
            nima_score=78, std_dev=1.2, confidence=0.85, overall=78.0
        ),
        composition=CompositionScore(
            rule_of_thirds=65, subject_position=70, horizon=75, balance=60, overall=67.5
        ),
        ai_feedback=AIFeedback(
            description="A sunset landscape",
            genre="landscape",
            strengths=["Good light", "Strong composition"],
            improvements=["Level the horizon"],
            mood="serene",
            score=75.0,
            reasoning="Well composed overall.",
        ),
        overall_score=73.2,
        grade=Grade.B,
    )


def _minimal_report() -> AnalysisReport:
    return AnalysisReport(
        image_meta=ImageMeta(path="test.jpg", width=100, height=100, format="JPEG"),
        technical=TechnicalScore(
            sharpness=50, exposure=50, noise=50, dynamic_range=50, overall=50.0
        ),
        overall_score=50.0,
        grade=Grade.C,
    )


class TestFormatJson:
    def test_returns_valid_json(self) -> None:
        result = format_json(_full_report())
        data = json.loads(result)
        assert isinstance(data, dict)

    def test_contains_overall_score(self) -> None:
        result = format_json(_full_report())
        data = json.loads(result)
        assert data["overall_score"] == 73.2

    def test_contains_grade(self) -> None:
        result = format_json(_full_report())
        data = json.loads(result)
        assert data["grade"] == "B"

    def test_contains_all_sections(self) -> None:
        result = format_json(_full_report())
        data = json.loads(result)
        assert "technical" in data
        assert "aesthetic" in data
        assert "composition" in data
        assert "ai_feedback" in data

    def test_missing_sections_are_null(self) -> None:
        result = format_json(_minimal_report())
        data = json.loads(result)
        assert data["aesthetic"] is None
        assert data["composition"] is None
        assert data["ai_feedback"] is None


class TestFormatMarkdown:
    def test_contains_header(self) -> None:
        result = format_markdown(_full_report())
        assert "# VisionScore Report:" in result

    def test_contains_overall_score(self) -> None:
        result = format_markdown(_full_report())
        assert "73.2/100" in result
        assert "Grade: B" in result

    def test_contains_score_summary(self) -> None:
        result = format_markdown(_full_report())
        assert "## Score Summary" in result

    def test_contains_ai_feedback_section(self) -> None:
        result = format_markdown(_full_report())
        assert "## AI Feedback" in result
        assert "landscape" in result

    def test_missing_aesthetic_shows_note(self) -> None:
        result = format_markdown(_minimal_report())
        assert "not available" in result

    def test_contains_footer(self) -> None:
        result = format_markdown(_full_report())
        assert "Generated by VisionScore" in result


class TestRenderReport:
    def test_does_not_raise(self) -> None:
        c = Console(file=open("/dev/null", "w"))
        render_report(_full_report(), c)

    def test_minimal_report_does_not_raise(self) -> None:
        c = Console(file=open("/dev/null", "w"))
        render_report(_minimal_report(), c)

    def test_with_warnings(self) -> None:
        c = Console(file=open("/dev/null", "w"))
        render_report(_full_report(), c, warnings=["Test warning"])
